name:   maple
channels:
  - conda
  - bioconda
  - conda-forge
  - anaconda
  - pyviz
  - bokeh
dependencies:
  - snakemake
  - python=3.9
  - minimap2
  - samtools
  - ngmerge
  - numba>=0.57 # pacmap installation is broken with numba 0.53
  - setuptools
  - wget
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - biopython
  - jupyter
  - jupyter_bokeh
  - umi_tools
  - medaka
  - nanoplot
  - natsort
  - hvplot
  - holoviews
  - datashader
  - bokeh
  - spatialpandas # allows for lasso selections of datashaded plots
  - selenium # for bokeh SVG export
  - webdriver-manager # for bokeh SVG export
  - panel
  - editdistance
  - racon
  - wheel
  - cython
  - tqdm
  - blat # for C3POa
  - mappy
  - pip
  - pip:
    - pyabpoa==1.4.0
    - pacmap