name: maple
channels:
  - conda
  # - bioconda # no ARM support except sometimes like for umicollapse? Idk, weird
  - conda-forge
  - anaconda
  - pyviz
  - bokeh
dependencies:
  - snakemake
  - python=3.11
  - automake
  - git-lfs
  # - minimap2
  # - samtools
  # - ngmerge
  - numba
  - graphviz # just for vizualizing the pipeline, not strictly required
  - setuptools
  - wget
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - biopython
  - jupyter
  - jupyter_bokeh
  # - medaka
  - keras-preprocessing # can help with medaka installation
  - natsort
  - hvplot
  - holoviews
  - datashader
  - bokeh==3.6 # pinned until bokeh 14502 is addressed https://github.com/bokeh/bokeh/issues/14502
  - spatialpandas # allows for lasso selections of datashaded plots
  - panel
  - editdistance
  # - racon # maybe dont need because it will be installed by C3POa?
  - wheel
  - cython
  - tqdm
  - openjdk
  - bioconda::umicollapse
  # - blat # for C3POa
  - mappy
  - pip
  - pip:
    # - pyabpoa==1.4.0
    - pacmap
    - selenium # for bokeh SVG export, conda installation is broken
    - nanoplot
    # - blat # for C3POa