name: maple
channels:
  - conda
  # - bioconda # no ARM support except sometimes like for umicollapse? Idk, weird
  - conda-forge
  - anaconda
  - pyviz
  - bokeh
dependencies:
  - snakemake
  - python
  - automake
  - git-lfs
  # - minimap2
  # - samtools
  # - ngmerge
  - numba=0.56 # pacmap is broken with numba 0.53, medaka is broken with numba 0.57
  - setuptools
  - wget
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - biopython
  - jupyter
  - jupyter_bokeh
  - umi_tools
  # - medaka
  - keras-preprocessing # can help with medaka installation
  - natsort
  - hvplot
  - holoviews
  - datashader
  - bokeh
  - spatialpandas # allows for lasso selections of datashaded plots
  - panel
  - editdistance
  # - racon # maybe dont need because it will be installed by C3POa?
  - wheel
  - cython
  - tqdm
  - openjdk
  - bioconda::umicollapse
  # - blat # for C3POa
  # - mappy
  - pymol-open-source # not used by pipeline, but nice to have for SequenceAnalyzer
  - pip
  - pip:
    # - pyabpoa==1.4.0
    - pacmap
    - selenium # for bokeh SVG export, conda installation is broken
    - nanoplot
    # - blat # for C3POa