name:   maple
channels:
  - conda
  - bioconda
  - conda-forge
  - anaconda
  - pyviz
dependencies:
  - snakemake
  - python
  - setuptools
  - wget
  - numpy
  - pandas
  - biopython
  - umi_tools
  - medaka
  - nanoplot
  - natsort
  - hvplot
  - holoviews
  - datashader
  - bokeh
  - selenium # for bokeh SVG export
  - webdriver-manager # for bokeh SVG export
  - panel==0.14.1 # temporary pin until I figure out the dependency issue with bokeh 3.0
  - editdistance
  - racon
  - wheel
  - cython
  - scipy
  - tqdm
  - blat
  - mappy
  - scikit-learn
  - pip
  - pip:
    - pyabpoa==1.4.0
    - pacmap