name: maple
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - python=3.11
  - automake
  - git-lfs
  - docutils=0.21 # pinned because 0.22 was not installing properly
  # - minimap2
  # - samtools
  # - ngmerge
  - numba
  - graphviz # just for vizualizing the pipeline, not strictly required
  - setuptools
  - wget
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - pacmap
  - nanoplot
  - biopython
  - jupyter
  - jupyter_bokeh
  # - medaka
  - keras-preprocessing # can help with medaka installation
  - natsort
  - hvplot
  - holoviews
  - datashader
  - py3dmol
  - bokeh # pinned until bokeh 14502 is addressed https://github.com/bokeh/bokeh/issues/14502
  - spatialpandas # allows for lasso selections of datashaded plots
  - panel
  - editdistance
  - racon # for c3poa
  - wheel
  - cython
  - tqdm
  - openjdk
  - bioconda::umicollapse
  - mappy
  - pip
  - selenium # for bokeh SVG export, conda installation is broken
  - chromedriver-binary